$("#")ifndef __$(ProjectName:upper())FRAME__
$("#")define __$(ProjectName:upper())FRAME__
/**
	Subclass of $(ProjectName)FrameBase, which is generated by Qt Designer.
	Event handlers for the frame are defined here.

	This file generated by $(Generator) <$(GeneratorURL)>.

	@file
	@author $(UserName)
	@date	$(Date)
*/

// Qt
$("#")include <QMainWindow>
$("#")include <QLabel>

namespace Ui
{
    class $(ProjectName)FrameBase;
}

/** Implementing $(ProjectName)FrameBase */
class $(ProjectName)Frame : public $(ProjectName)FrameBase
{
	Q_OBJECT
	
public:
	/** Constructor */
	$(ProjectName)Frame( QWidget* parent = 0 );
	/** Destructor */
	~$(ProjectName)Frame();

public Q_SLOTS:
	void OnAbout();
	void SetStatusBarText( const QString& text );

private:	
	QLabel* m_statusBarTextWidget;
};

$("#")endif // __$(ProjectName:upper())FRAME__
