/**
	Defines the $(ProjectName) application. This is the entry point for the main
	wxWidgets application.
	
	This file generated by $(Generator) <$(GeneratorURL)>.
	
	@file
	@author $(UserName)
	@data	$(Date)
*/
$(#)ifndef $(ProjectName)_H
$(#)define $(ProjectName)_H

$(#)include <wx/app.h>

class $(ProjectName)App : public wxApp
{
public:
	$(ProjectName)App();
	~$(ProjectName)App();

protected:
	virtual bool OnInit();
	virtual int OnExit();
};
$(#)endif // $(ProjectName)_H

