$("#")ifndef __$(ProjectName:upper())FRAME__
$("#")define __$(ProjectName:upper())FRAME__

/**
	Subclass of $(ProjectName)FrameBase, which is generated by wxFormBuilder.
	Event handlers for the frame are defined here.

	This file generated by $(Generator) <$(GeneratorURL)>.

	@file
	@author $(UserName)
	@data	$(Date)
*/

$("#")include "$(ProjectName)_GUI.h"

/** Implementing $(ProjectName)FrameBase */
class $(ProjectName)Frame : public $(ProjectName)FrameBase
{
protected:
	// Handlers for $(ProjectName)FrameBase events.
	void OnExit( wxCommandEvent& event );
	void OnAbout( wxCommandEvent& event );

public:
	/** Constructor */
	$(ProjectName)Frame( wxWindow* parent );
};

$("#")endif // __$(ProjectName:upper())FRAME__
